---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[security_compliance::default]
    verifier:
      inspec_tests:
        - inspec/profiles/security_checks
